LIST_FIELDS = {
  "Information about subcontracting": "likely_subcontracted", 
  "Contract number and value:": "value", 
  "Common procurement vocabulary (CPV):": "cpv", 
  "Publication date of the procurement notice:": "publication_date", 
  "NAME AND ADDRESS OF ECONOMIC OPERATOR IN FAVOUR OF WHOM THE CONTRACT AWARD HAS BEEN TAKEN": "tenderer", 
  "File reference number attributed by the contracting entity:": "authority_ref", 
  "Name and address of economic operator in favour of whom a contract award decision has been taken:": "tenderer", 
  "Type of contract and location of works, place of delivery or of performance": "type", 
  "Total final value of contract(s)": "total_value", 
  "Information about offers": "num_offers", 
  "Type of procedure:": "procedure_type", 
  "Information on value of contract:": "value", 
  "Previous publication(s) concerning the same contract:": "previous_notices", 
  "Previous publication(s) concerning the same contract": "previous_notices", 
  "Name and address of economic operator in favour of whom a contract award decision has been taken": None, 
  "null": None, 
  "Previous publication(s) in Official Journal S:": "previous_notices", 
  "Number and titles of the lots:": "lot_nr_title", 
  "NAME, ADDRESSES AND CONTACT POINT(S)": "authority", 
  "Information about a framework agreement or a dynamic purchasing system (DPS)": None, 
  "An electronic auction was used:": "electronic", 
  "Short description of the contract or purchase(s):": "description", 
  "An electronic auction has been used": "electronic", 
  "Date of contract award:": "award_date", 
  "File reference number attributed by the contracting authority/entity": "authority_ref", 
  "Type of contract and location of works, place of delivery or of performance:": "type", 
  "File reference number attributed by the contracting authority": "authority_ref", 
  "Number of tenders received:": "num_offers", 
  "Award criteria:": "award_criteria", 
  "Lodging of appeals:": "appeals_body", 
  "Name and address of successful tenderer:": "tenderer", 
  "Main activity": "services_covered", 
  "Type of the contracting authority and main activity or activities:": "authority_type", 
  "Type of procedure": "procedure_type", 
  "Name and address of the successful tenderer:": "tenderer", 
  "Additional information:": "additional_info", 
  "ADDITIONAL INFORMATION": "additional_info", 
  "Award criteria": "award_criteria", 
  "Information on value of contract": "value", 
  "Contract award on behalf of other contracting authorities/entities": "behalf_of", 
  "NUMBER OF OFFERS RECEIVED:": "num_offers", 
  "Name and address of the competent authority:": "authority", 
  "Award and contract value": "value", 
  "Information about European Union funds": "eu_funds", 
  "Name and address of economic operator in favour of whom the contract award decision has been taken": "tenderer", 
  "Short description of the contract or purchase(s)": "description", 
  "Duration of contract:": "duration", 
  "Title attributed to the contract:": "title", 
  "Lodging of appeals": "appeals_body", 
  "The notice involves": "involves", 
  "Date of award of the contract:": "award_date", 
  "Contract value:": "value", 
  "AWARD AND CONTRACT VALUE": None, 
  "Title attributed to the contract by the contracting authority:": "title", 
  "CONTRACT RELATED TO A PROJECT AND/OR PROGRAMME FINANCED BY COMMUNITY FUNDS": "eu_funds", 
  "Language(s) in which tenders or requests to participate may be drawn up": None, 
  "Type of the contracting authority": "authority_type", 
  "Name, addresses and contact point(s)": "authority", 
  "The notice involves:": "involves", 
  "Type of the contracting authority and main activity or activities: ": "authority_type", 
  "TYPE OF THE CONTRACTING AUTHORITY AND MAIN ACTIVITY OR ACTIVITIES": "authority_type", 
  "Name, address and nationality of successful tenderer:": "tenderer", 
  "THE CONTRACT IS LIKELY TO BE SUB-CONTRACTED": "likely_subcontracted", 
  "Lot number and lot title:": "lot_nr_title", 
  "Title attributed to the contract": "title", 
  "Overall score of chosen tender:": "score_chosen_tender", 
  "Service from which information about the lodging of appeals may be obtained": "appeals_info", 
  "DATE OF DISPATCH OF THIS NOTICE:": "notice_date", 
  "Contract covered by the Government Procurement Agreement (GPA):": "gpa_covered", 
  "Contract covered by the Government Procurement Agreement (GPA)": "gpa_covered", 
  "Publication reference:": "reference", 
  "Contract related to a project and/or programme financed by EU funds: ": "eu_funds", 
  "NAME AND ADDRESS OF ECONOMIC OPERATOR IN FAVOUR OF WHOM A CONTRACT AWARD DECISION HAS BEEN TAKEN": "tenderer", 
  "Name, addresses and contact point(s):": "authority", 
  "Date of the contract award:": "notice_date", 
  "Name and address of economic operator to whom the contract has been awarded:": "tenderer", 
  "Contract covered by the Government Procurement Agreement (GPA): ": "gpa_covered", 
  "INFORMATION ON VALUE OF CONTRACT": "value", 
  "Contracting authority:": "authority", 
  "Total final value of contract(s): ": "total_value", 
  "Description": "description", 
  "Information about electronic auction": "electronic", 
  "An electronic auction has been used:": "electronic", 
  "Time-limit": None, 
  "Type of award envisaged:": "award_type", 
  "File reference number attributed by the contracting authority:": "authority_ref", 
  "Body responsible for appeal procedures": "appeals_body", 
  "Total final value of contract(s):": "total_value", 
  "DAC code:": "dac_code", 
  "Legal basis:": "legal_basis", 
  "Date of dispatch of this notice:": "notice_date", 
  "Body responsible for appeal procedures:": "appeals_body", 
  "Contract related to a project and/or programme financed by EU funds:": "eu_funds", 
  "Common procurement vocabulary (CPV)": "cpv", 
  "Type of contracting authority and main activity or activities:": "authority_type", 
  "Previous notice(s) published concerning the same contract:": "previous_notices", 
  "Price paid for bargain purchases": None, 
  "TOTAL FINAL VALUE OF CONTRACT(S)": None, 
  "Value of the contract:": "value", 
  "Date of contract award decision:": "award_date", 
  "Contract award on behalf of other contracting entities": "behalf_of", 
  "Total score of the selected tender:": "score_chosen_tender", 
  "Services and areas potentially covered by the award:": "services_covered", 
  "Number of offers received:": "num_offers", 
  "Information about Government Procurement Agreement (GPA)": "gpa_covered", 
  "Contract award on behalf of other contracting authorities": "behalf_of", 
  "Name and address of economic operator to whom the contract has been awarded: ": "tenderer", 
  "The contract is likely to be subcontracted:": "likely_subcontracted"
}
